// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a fresh random 32-byte group key.
Future<Uint8List> generateGroupKey() =>
    RustLib.instance.api.crateApiGenerateGroupKey();

/// Derive a stable group ID string from a 32-byte group key.
Future<String> groupIdFromKey({required List<int> key}) =>
    RustLib.instance.api.crateApiGroupIdFromKey(key: key);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppNode>>
abstract class AppNode implements RustOpaqueInterface {
  /// Add a map pin to a group and optionally publish via gossip.
  Future<void> addPin({
    required String groupId,
    required String label,
    required String location,
  });

  /// Record the current location and optionally publish via gossip.
  Future<void> checkIn({
    required String groupId,
    String? stageId,
    String? customLocation,
  });

  /// Connect this node to the Festival Durable Object relay at `url`.
  ///
  /// Spawns a background task that receives messages and feeds them into
  /// the dispatch pipeline. The WS sink is stored on the node for sending.
  /// Auto-reconnects on disconnect with exponential backoff.
  Future<void> connectRelay({required String url});

  /// Open (or create) the node database at `db_path`.
  static Future<AppNode> create({required String dbPath}) =>
      RustLib.instance.api.crateApiAppNodeCreate(dbPath: dbPath);

  /// Create a new group and return its ID + shareable invite payload.
  Future<GroupCreateResultDto> createGroup({
    required String festivalId,
    required String name,
    required String displayName,
  });

  /// Create an in-memory node (useful for testing).
  static Future<AppNode> createInMemory() =>
      RustLib.instance.api.crateApiAppNodeCreateInMemory();

  /// Delete a group by ID.
  Future<void> deleteGroup({required String id});

  /// Derive the Ed25519 identity from a WebAuthn PRF output (32 bytes).
  /// Returns the hex-encoded Ed25519 public key.
  Future<String> deriveIdentityFromPrf({required List<int> prfOutput});

  /// Load the stored attestation, if any.
  Future<AttestationDto?> getAttestation();

  /// Get the current authentication state.
  Future<AuthStateDto> getAuthState();

  /// Return paginated chat history for a topic string.
  Future<List<ChatMessageDto>> getChatHistory({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Fetch chat messages for a topic with pagination.
  Future<List<ChatMessageDto>> getChatMessages({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Read the current state of a group from the local Yrs doc.
  Future<GroupStateDto> getGroupState({required String groupId});

  /// Return all groups for the given festival.
  Future<List<GroupInfo>> getGroups({required String festivalId});

  /// Return the local identity (user_id + optional display_name).
  Future<IdentityDto> getIdentity();

  /// Get the hex-encoded Ed25519 public key of the local identity.
  Future<String> getPublicKeyHex();

  /// Return the set IDs that are starred for the given festival.
  Future<List<String>> getStars({required String festivalId});

  /// Join an existing group from an invite payload.
  Future<GroupJoinResultDto> joinGroup({
    required String invitePayload,
    required String displayName,
  });

  /// Leave a group.
  Future<void> leaveGroup({required String groupId});

  /// Broadcast a chat message on the given gossip topic.
  Future<void> publishChat({
    required String topic,
    required ChatMessageDto message,
  });

  /// Persist a group record for a festival.
  Future<void> saveGroup({
    required String id,
    required String festivalId,
    required String name,
    required List<int> key,
  });

  /// Send a festival chat message (plaintext) and broadcast it via gossip if
  /// networking is active.  Returns the persisted message.
  ///
  /// WS relay delivery should be performed separately by the caller via
  /// `connect_relay`.
  Future<ChatMessageDto> sendFestivalChat({
    required String festivalId,
    String? stageId,
    required String text,
  });

  /// Send an encrypted group chat message and broadcast it via gossip if
  /// networking is active.  Returns the persisted message.
  Future<ChatMessageDto> sendGroupChat({
    required String groupId,
    required String text,
  });

  /// Persist a display name for the local user.
  Future<void> setDisplayName({required String name});

  /// Cache a festival's Ed25519 public key (hex-encoded, 64 chars).
  /// Call this after fetching from `GET /festivals/:id/public-key` on the
  /// Dart/Flutter side.
  Future<void> setFestivalPublicKey({
    required String festivalId,
    required String hexKey,
  });

  /// Sign an arbitrary message with the local Ed25519 identity key.
  /// Used for admin operations (signing paths, challenges, etc.).
  /// Returns the hex-encoded signature.
  Future<String> signMessage({required String message});

  /// Store an attestation received from the MainDO.
  Future<void> storeAttestation({
    required String message,
    required String signature,
    required String issuer,
  });

  /// Subscribe to all chat topics for a festival (general + campsite + per-stage).
  Future<void> subscribeChatTopics({
    required String festivalId,
    required List<String> stageIds,
  });

  /// Subscribe to the gossip topic for a festival, using the iroh-gossip
  /// layer (if networking was started).
  Future<void> subscribeFestival({required String festivalId});

  /// Toggle a star on a set. Returns the new starred state (`true` = now starred).
  Future<bool> toggleStar({required String festivalId, required String setId});

  /// Update the shared stars for the current user in a group.
  Future<void> updateSharedStars({
    required String groupId,
    required List<String> setIds,
  });
}

class AttestationDto {
  final String message;
  final String signature;
  final String issuer;

  const AttestationDto({
    required this.message,
    required this.signature,
    required this.issuer,
  });

  @override
  int get hashCode => message.hashCode ^ signature.hashCode ^ issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttestationDto &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          issuer == other.issuer;
}

class AuthStateDto {
  final String state;
  final String? expiresAt;

  const AuthStateDto({required this.state, this.expiresAt});

  @override
  int get hashCode => state.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          expiresAt == other.expiresAt;
}

class ChatMessageDto {
  final String id;
  final String userId;
  final String displayName;
  final String text;
  final String topic;
  final String? stageId;
  final String timestamp;

  const ChatMessageDto({
    required this.id,
    required this.userId,
    required this.displayName,
    required this.text,
    required this.topic,
    this.stageId,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      displayName.hashCode ^
      text.hashCode ^
      topic.hashCode ^
      stageId.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          displayName == other.displayName &&
          text == other.text &&
          topic == other.topic &&
          stageId == other.stageId &&
          timestamp == other.timestamp;
}

class GroupCreateResultDto {
  final String groupId;
  final String invitePayload;

  const GroupCreateResultDto({
    required this.groupId,
    required this.invitePayload,
  });

  @override
  int get hashCode => groupId.hashCode ^ invitePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupCreateResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          invitePayload == other.invitePayload;
}

class GroupInfo {
  final String id;
  final String name;

  const GroupInfo({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class GroupJoinResultDto {
  final String groupId;

  const GroupJoinResultDto({required this.groupId});

  @override
  int get hashCode => groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupJoinResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId;
}

class GroupMemberDto {
  final String userId;
  final String displayName;
  final String status;
  final String? stageId;
  final String? customLocation;

  const GroupMemberDto({
    required this.userId,
    required this.displayName,
    required this.status,
    this.stageId,
    this.customLocation,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      stageId.hashCode ^
      customLocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          status == other.status &&
          stageId == other.stageId &&
          customLocation == other.customLocation;
}

class GroupPinDto {
  final String id;
  final String label;
  final String location;
  final String pinnedBy;

  const GroupPinDto({
    required this.id,
    required this.label,
    required this.location,
    required this.pinnedBy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ location.hashCode ^ pinnedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupPinDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          location == other.location &&
          pinnedBy == other.pinnedBy;
}

class GroupStateDto {
  final String name;
  final List<GroupMemberDto> members;
  final List<GroupPinDto> pins;

  const GroupStateDto({
    required this.name,
    required this.members,
    required this.pins,
  });

  @override
  int get hashCode => name.hashCode ^ members.hashCode ^ pins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupStateDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          members == other.members &&
          pins == other.pins;
}

class IdentityDto {
  final String userId;
  final String? displayName;

  const IdentityDto({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}
