// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_sync_status`, `parse_json_array`, `read_lineup_from_doc`

/// Generate a fresh random 32-byte group key.
Future<Uint8List> generateGroupKey() =>
    RustLib.instance.api.crateApiGenerateGroupKey();

/// Derive a stable group ID string from a 32-byte group key.
Future<String> groupIdFromKey({required List<int> key}) =>
    RustLib.instance.api.crateApiGroupIdFromKey(key: key);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppNode>>
abstract class AppNode implements RustOpaqueInterface {
  /// Add a map pin to a group and optionally publish via gossip.
  Future<void> addPin({
    required String groupId,
    required String label,
    required String location,
  });

  /// Record the current location and optionally publish via gossip.
  Future<void> checkIn({
    required String groupId,
    String? stageId,
    String? customLocation,
  });

  /// Connect this node to the Festival Durable Object relay at `url`.
  ///
  /// `festival_id` is used to look up the cached Ed25519 public key for
  /// verifying signed updates. Call `set_festival_public_key` first.
  Future<void> connectRelay({required String url, required String festivalId});

  /// Open (or create) the node database at `db_path`.
  static Future<AppNode> create({required String dbPath}) =>
      RustLib.instance.api.crateApiAppNodeCreate(dbPath: dbPath);

  /// Create a new group and return its ID + shareable invite payload.
  Future<GroupCreateResultDto> createGroup({
    required String festivalId,
    required String name,
    required String displayName,
  });

  /// Create an in-memory node (useful for testing).
  static Future<AppNode> createInMemory() =>
      RustLib.instance.api.crateApiAppNodeCreateInMemory();

  /// Delete a group by ID.
  Future<void> deleteGroup({required String id});

  /// Derive the Ed25519 identity from a WebAuthn PRF output (32 bytes).
  Future<String> deriveIdentityFromPrf({required List<int> prfOutput});

  /// Load the stored attestation, if any.
  Future<AttestationDto?> getAttestation();

  /// Get the current authentication state.
  Future<AuthStateDto> getAuthState();

  /// Return paginated chat history for a topic string.
  Future<List<ChatMessageDto>> getChatHistory({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Fetch chat messages for a topic with pagination.
  Future<List<ChatMessageDto>> getChatMessages({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Read the current state of a group from the local Yrs doc.
  Future<GroupStateDto> getGroupState({required String groupId});

  /// Return all groups for the given festival.
  Future<List<GroupInfo>> getGroups({required String festivalId});

  /// Return the local identity (user_id + optional display_name).
  Future<IdentityDto> getIdentity();

  /// Read the lineup from the local Yrs doc for a festival.
  ///
  /// The Yrs doc at `festival/{id}/state` has separate root-map keys:
  /// `"stages"`, `"days"`, `"sets"` — each a JSON array string that
  /// arrives via signed gossip updates and merges independently.
  ///
  /// Returns `None` if no lineup data has synced yet.
  Future<LineupDto?> getLineup({required String festivalId});

  /// Get the hex-encoded Ed25519 public key of the local identity.
  Future<String> getPublicKeyHex();

  /// Return the set IDs that are starred for the given festival.
  Future<List<String>> getStars({required String festivalId});

  /// Join an existing group from an invite payload.
  Future<GroupJoinResultDto> joinGroup({
    required String invitePayload,
    required String displayName,
  });

  /// Leave a group.
  Future<void> leaveGroup({required String groupId});

  /// Broadcast a chat message on the given gossip topic.
  Future<void> publishChat({
    required String topic,
    required ChatMessageDto message,
  });

  /// Persist a group record for a festival.
  Future<void> saveGroup({
    required String id,
    required String festivalId,
    required String name,
    required List<int> key,
  });

  /// Send a festival chat message (plaintext) and broadcast it via gossip if
  /// networking is active. Returns the persisted message.
  Future<ChatMessageDto> sendFestivalChat({
    required String festivalId,
    String? stageId,
    required String text,
  });

  /// Send an encrypted group chat message and broadcast it via gossip if
  /// networking is active. Returns the persisted message.
  Future<ChatMessageDto> sendGroupChat({
    required String groupId,
    required String text,
  });

  /// Persist a display name for the local user.
  Future<void> setDisplayName({required String name});

  /// Cache a festival's Ed25519 public key (hex-encoded, 64 chars).
  Future<void> setFestivalPublicKey({
    required String festivalId,
    required String hexKey,
  });

  /// Sign an arbitrary message with the local Ed25519 identity key.
  Future<String> signMessage({required String message});

  /// Store an attestation received from the MainDO.
  Future<void> storeAttestation({
    required String message,
    required String signature,
    required String issuer,
  });

  /// Subscribe to all chat topics for a festival (general + campsite + per-stage).
  Future<void> subscribeChatTopics({
    required String festivalId,
    required List<String> stageIds,
  });

  /// Subscribe to the gossip topic for a festival and perform a state vector
  /// exchange with the DO so we only receive updates we don't already have.
  Future<void> subscribeFestival({required String festivalId});

  /// Toggle a star on a set. Returns the new starred state (`true` = now starred).
  Future<bool> toggleStar({required String festivalId, required String setId});

  /// Update the shared stars for the current user in a group.
  Future<void> updateSharedStars({
    required String groupId,
    required List<String> setIds,
  });

  /// Watch chat messages for a topic — emits current messages, then updates.
  Future<Stream<List<ChatMessageDto>>> watchChat({
    required String topic,
    required int lastN,
  });

  /// Watch group state — emits current state, then updates on changes.
  Future<Stream<GroupStateDto>> watchGroupState({required String groupId});

  /// Watch festival lineup — emits current state, then updates on changes.
  ///
  /// The stream emits the current lineup immediately, then re-emits whenever
  /// the lineup document is updated (via sync or local changes).
  Future<Stream<LineupDto?>> watchLineup({required String festivalId});

  /// Watch sync status — emits current status, then updates on changes.
  Future<Stream<SyncStatusDto>> watchSyncStatus();
}

class AttestationDto {
  final String message;
  final String signature;
  final String issuer;

  const AttestationDto({
    required this.message,
    required this.signature,
    required this.issuer,
  });

  @override
  int get hashCode => message.hashCode ^ signature.hashCode ^ issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttestationDto &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          issuer == other.issuer;
}

class AuthStateDto {
  final String state;
  final String? expiresAt;

  const AuthStateDto({required this.state, this.expiresAt});

  @override
  int get hashCode => state.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          expiresAt == other.expiresAt;
}

class ChatMessageDto {
  final String id;
  final String userId;
  final String displayName;
  final String text;
  final String topic;
  final String? stageId;
  final String timestamp;

  const ChatMessageDto({
    required this.id,
    required this.userId,
    required this.displayName,
    required this.text,
    required this.topic,
    this.stageId,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      displayName.hashCode ^
      text.hashCode ^
      topic.hashCode ^
      stageId.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          displayName == other.displayName &&
          text == other.text &&
          topic == other.topic &&
          stageId == other.stageId &&
          timestamp == other.timestamp;
}

class GroupCreateResultDto {
  final String groupId;
  final String invitePayload;

  const GroupCreateResultDto({
    required this.groupId,
    required this.invitePayload,
  });

  @override
  int get hashCode => groupId.hashCode ^ invitePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupCreateResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          invitePayload == other.invitePayload;
}

class GroupInfo {
  final String id;
  final String name;

  const GroupInfo({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class GroupJoinResultDto {
  final String groupId;

  const GroupJoinResultDto({required this.groupId});

  @override
  int get hashCode => groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupJoinResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId;
}

class GroupMemberDto {
  final String userId;
  final String displayName;
  final String status;
  final String? stageId;
  final String? customLocation;

  const GroupMemberDto({
    required this.userId,
    required this.displayName,
    required this.status,
    this.stageId,
    this.customLocation,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      stageId.hashCode ^
      customLocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          status == other.status &&
          stageId == other.stageId &&
          customLocation == other.customLocation;
}

class GroupPinDto {
  final String id;
  final String label;
  final String location;
  final String pinnedBy;

  const GroupPinDto({
    required this.id,
    required this.label,
    required this.location,
    required this.pinnedBy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ location.hashCode ^ pinnedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupPinDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          location == other.location &&
          pinnedBy == other.pinnedBy;
}

class GroupStateDto {
  final String name;
  final List<GroupMemberDto> members;
  final List<GroupPinDto> pins;

  const GroupStateDto({
    required this.name,
    required this.members,
    required this.pins,
  });

  @override
  int get hashCode => name.hashCode ^ members.hashCode ^ pins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupStateDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          members == other.members &&
          pins == other.pins;
}

class IdentityDto {
  final String userId;
  final String? displayName;

  const IdentityDto({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}

class LineupDayDto {
  final String id;
  final String label;
  final int num;
  final String month;

  const LineupDayDto({
    required this.id,
    required this.label,
    required this.num,
    required this.month,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ num.hashCode ^ month.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDayDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          num == other.num &&
          month == other.month;
}

class LineupDto {
  final List<LineupStageDto> stages;
  final List<LineupDayDto> days;
  final List<LineupSetDto> sets;

  const LineupDto({
    required this.stages,
    required this.days,
    required this.sets,
  });

  @override
  int get hashCode => stages.hashCode ^ days.hashCode ^ sets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDto &&
          runtimeType == other.runtimeType &&
          stages == other.stages &&
          days == other.days &&
          sets == other.sets;
}

class LineupSetDto {
  final String id;
  final String day;
  final String stage;
  final String artist;
  final int startMin;
  final int durationMin;
  final String genre;
  final bool cancelled;

  const LineupSetDto({
    required this.id,
    required this.day,
    required this.stage,
    required this.artist,
    required this.startMin,
    required this.durationMin,
    required this.genre,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      day.hashCode ^
      stage.hashCode ^
      artist.hashCode ^
      startMin.hashCode ^
      durationMin.hashCode ^
      genre.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupSetDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          day == other.day &&
          stage == other.stage &&
          artist == other.artist &&
          startMin == other.startMin &&
          durationMin == other.durationMin &&
          genre == other.genre &&
          cancelled == other.cancelled;
}

class LineupStageDto {
  final String id;
  final String name;
  final String short;
  final String color;
  final int order;

  const LineupStageDto({
    required this.id,
    required this.name,
    required this.short,
    required this.color,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      short.hashCode ^
      color.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupStageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          short == other.short &&
          color == other.color &&
          order == other.order;
}

/// Per-resource sync status.
class ResourceSyncStatusDto {
  final String id;
  final bool syncing;
  final String? lastSynced;
  final String? error;

  const ResourceSyncStatusDto({
    required this.id,
    required this.syncing,
    this.lastSynced,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^ syncing.hashCode ^ lastSynced.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceSyncStatusDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncing == other.syncing &&
          lastSynced == other.lastSynced &&
          error == other.error;
}

/// Overall sync status for the node.
class SyncStatusDto {
  final bool syncing;
  final List<ResourceSyncStatusDto> resources;
  final int pendingOps;

  const SyncStatusDto({
    required this.syncing,
    required this.resources,
    required this.pendingOps,
  });

  @override
  int get hashCode =>
      syncing.hashCode ^ resources.hashCode ^ pendingOps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          syncing == other.syncing &&
          resources == other.resources &&
          pendingOps == other.pendingOps;
}
