// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `deregister_group_resources`, `ensure_group_chat_access`, `flush_pending_group_updates`, `group_id_from_chat_topic`, `publish_group_state_update`, `reconcile_shared_stars`, `register_group_resources`, `schedule_pending_group_retry`, `send_group_state_update`, `send_pending_group_update`

Future<List<MeshtasticDebugDeviceDto>> meshtasticDebugScan({
  required int scanMs,
}) => RustLib.instance.api.crateApiMeshtasticDebugScan(scanMs: scanMs);

Future<MeshtasticDebugReportDto> meshtasticDebugProbe({
  required String deviceId,
  required List<int> body,
  required int listenMs,
  required bool send,
}) => RustLib.instance.api.crateApiMeshtasticDebugProbe(
  deviceId: deviceId,
  body: body,
  listenMs: listenMs,
  send: send,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppNode>>
abstract class AppNode implements RustOpaqueInterface {
  /// Add a map pin to a group and optionally publish via gossip.
  Future<void> addPin({
    required String groupId,
    required String label,
    required String location,
  });

  /// Record the current location and optionally publish via gossip.
  Future<void> checkIn({
    required String groupId,
    String? stageId,
    String? customLocation,
  });

  /// Explicitly trigger a proactive BLE connection to a device for verification or sync.
  Future<void> connectPeer({required String deviceId});

  /// Connect this node to the Festival Durable Object relay at `url`.
  ///
  /// `festival_id` is used to look up the cached Ed25519 public key for
  /// verifying signed updates. Call `set_festival_public_key` first.
  Future<void> connectRelay({required String url, required String festivalId});

  /// Open (or create) the node database at `db_path` with full networking
  /// (iroh endpoint, gossip, and BLE transport if available).
  static Future<AppNode> create({required String dbPath}) =>
      RustLib.instance.api.crateApiAppNodeCreate(dbPath: dbPath);

  /// Create a new group, register resources, subscribe, and broadcast
  /// the initial state. Returns the group ID + shareable invite payload.
  Future<GroupCreateResultDto> createGroup({
    required String festivalId,
    required String name,
    required String displayName,
  });

  /// Create an in-memory node (useful for testing).
  static Future<AppNode> createInMemory() =>
      RustLib.instance.api.crateApiAppNodeCreateInMemory();

  /// Delete a group by ID.
  Future<void> deleteGroup({required String id});

  /// Derive the Ed25519 identity from a WebAuthn PRF output (32 bytes).
  Future<String> deriveIdentityFromPrf({required List<int> prfOutput});

  /// Stop the active Festival DO relay and its reconnect loop.
  Future<void> disconnectRelay();

  /// Load the stored attestation, if any.
  Future<AttestationDto?> getAttestation();

  /// Get the current authentication state.
  Future<AuthStateDto> getAuthState();

  /// Return paginated chat history for a topic string.
  Future<List<ChatMessageDto>> getChatHistory({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Fetch chat messages for a topic with pagination.
  Future<List<ChatMessageDto>> getChatMessages({
    required String topic,
    required int limit,
    required int offset,
  });

  /// Read the current state of a group from the local Yrs doc.
  Future<GroupStateDto> getGroupState({required String groupId});

  /// Return all groups for the given festival.
  Future<List<GroupInfo>> getGroups({required String festivalId});

  /// Return the local identity (user_id + optional display_name).
  Future<IdentityDto> getIdentity();

  /// Reconstruct the invite payload URI for an existing group.
  ///
  /// Returns `offbeat://group/{festival_id}/{group_id}/{base64url(key)}`
  /// or `None` if the group is not found.
  Future<String?> getInvitePayload({
    required String groupId,
    required String festivalId,
  });

  /// Read the lineup from the local Yrs doc for a festival.
  ///
  /// Returns `None` if no lineup data has synced yet.
  Future<LineupDto?> getLineup({required String festivalId});

  /// Return the number of active direct peers (those with gossip status "active").
  Future<int> getPeerCount();

  /// Return a snapshot of all known peers for the UI.
  Future<List<PeerStatusInfo>> getPeerList();

  /// Get the hex-encoded Ed25519 public key of the local identity.
  Future<String> getPublicKeyHex();

  /// Return the set IDs that are starred for the given festival.
  Future<List<String>> getStars({required String festivalId});

  /// Get a snapshot of transport status (no rate computation).
  Future<TransportStatusDto> getTransportStatus();

  /// Read the weather forecast from the local Yrs doc for a festival.
  ///
  /// Returns `None` if no weather data has synced yet.
  Future<WeatherForecastDto?> getWeather({required String festivalId});

  /// Join an existing group, register resources, subscribe, and trigger
  /// SV exchange + chat catchup.
  Future<GroupJoinResultDto> joinGroup({
    required String invitePayload,
    required String festivalId,
    required String displayName,
  });

  /// Leave a group.
  Future<void> leaveGroup({required String groupId});

  /// Listen for Meshtastic group chat frames and apply matching local groups.
  Future<MeshtasticDebugReportDto> meshtasticListenApplyGroupChats({
    required String deviceId,
    required String festivalId,
    required int listenMs,
  });

  /// Send a compact encrypted group chat through a selected Meshtastic radio.
  Future<MeshtasticDebugReportDto> meshtasticSendGroupChat({
    required String deviceId,
    required String groupId,
    required String text,
  });

  /// Manually trigger a gossip join nudge for all currently visible BLE peers.
  /// Useful for breaking sync deadlocks.
  Future<void> nudgeGossip();

  /// Broadcast a chat message on the given gossip topic.
  Future<void> publishChat({
    required String topic,
    required ChatMessageDto message,
  });

  /// Cycle the BLE transport (stop then start).
  Future<void> restartBle();

  /// Persist a group record for a festival.
  Future<void> saveGroup({
    required String id,
    required String festivalId,
    required String name,
    required List<int> key,
  });

  /// Send a festival chat message (plaintext) and broadcast it via gossip if
  /// networking is active. Returns the persisted message.
  Future<ChatMessageDto> sendFestivalChat({
    required String festivalId,
    String? stageId,
    required String text,
  });

  /// Send an encrypted group chat message and broadcast it via gossip if
  /// networking is active. Returns the persisted message.
  Future<ChatMessageDto> sendGroupChat({
    required String groupId,
    required String text,
  });

  /// Persist a display name for the local user.
  Future<void> setDisplayName({required String name});

  /// Cache a festival's Ed25519 public key (hex-encoded, 64 chars).
  Future<void> setFestivalPublicKey({
    required String festivalId,
    required String hexKey,
  });

  /// Sign an arbitrary message with the local Ed25519 identity key.
  Future<String> signMessage({required String message});

  /// Start BLE auto-connection background tasks.
  ///
  /// Spawns discovery tick, reconnect tick, and gossip event pump tasks that
  /// transition BLE-discovered peers to gossip-connected. Call after
  /// subscribing to festival/group topics.
  Future<void> startBleSync();

  /// Stop the BLE background tasks.
  Future<void> stopBleSync();

  /// Store an attestation received from the MainDO.
  Future<void> storeAttestation({
    required String message,
    required String signature,
    required String issuer,
  });

  /// Subscribe to all chat topics for a festival (general + campsite + per-stage).
  Future<void> subscribeChatTopics({
    required String festivalId,
    required List<String> stageIds,
  });

  /// Subscribe to the gossip topic for a festival and perform a state vector
  /// exchange with the DO so we only receive updates we don't already have.
  ///
  /// Registers the festival as a resource in the registry, then delegates
  /// subscribe + catch-up to the SyncOrchestrator.
  Future<void> subscribeFestival({required String festivalId});

  /// Subscribe to all group topics for a festival and sync state.
  ///
  /// Loads groups from SQLite, registers their resources (state + chat),
  /// and triggers a sync via the WS relay if connected.
  Future<void> subscribeGroups({required String festivalId});

  /// Toggle a personal star and reconcile the resulting schedule into every
  /// encrypted group for this festival.
  Future<bool> toggleStar({required String festivalId, required String setId});

  /// Update the shared stars for the current user in a group.
  Future<void> updateSharedStars({
    required String groupId,
    required List<String> setIds,
  });

  /// Watch chat messages for a topic — emits current messages, then updates.
  Future<Stream<List<ChatMessageDto>>> watchChat({
    required String topic,
    required int lastN,
  });

  /// Watch group state — emits current state, then updates on changes.
  Future<Stream<GroupStateDto>> watchGroupState({required String groupId});

  /// Watch festival lineup — emits current state, then updates on changes.
  ///
  /// The stream emits the current lineup immediately, then re-emits whenever
  /// the lineup document is updated (via sync or local changes).
  Future<Stream<LineupDto?>> watchLineup({required String festivalId});

  /// Watch the peer list — polls every second and emits whenever the
  /// snapshot changes (peer count or any entry status).
  Future<Stream<List<PeerStatusInfo>>> watchPeerList();

  /// Watch sync status — emits current status, then updates on changes.
  Future<Stream<SyncStatusDto>> watchSyncStatus();

  /// Watch transport status — emits relay + BLE state with bandwidth
  /// rates computed by diffing cumulative counters every second.
  Future<Stream<TransportStatusDto>> watchTransportStatus();

  /// Watch weather forecast — emits current forecast, then updates on changes.
  Future<Stream<WeatherForecastDto?>> watchWeather({
    required String festivalId,
  });
}
