// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppNodePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppNode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AttestationDto dco_decode_attestation_dto(dynamic raw);

  @protected
  AuthStateDto dco_decode_auth_state_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AttestationDto dco_decode_box_autoadd_attestation_dto(dynamic raw);

  @protected
  ChatMessageDto dco_decode_box_autoadd_chat_message_dto(dynamic raw);

  @protected
  ChatMessageDto dco_decode_chat_message_dto(dynamic raw);

  @protected
  GroupCreateResultDto dco_decode_group_create_result_dto(dynamic raw);

  @protected
  GroupInfo dco_decode_group_info(dynamic raw);

  @protected
  GroupJoinResultDto dco_decode_group_join_result_dto(dynamic raw);

  @protected
  GroupMemberDto dco_decode_group_member_dto(dynamic raw);

  @protected
  GroupPinDto dco_decode_group_pin_dto(dynamic raw);

  @protected
  GroupStateDto dco_decode_group_state_dto(dynamic raw);

  @protected
  IdentityDto dco_decode_identity_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChatMessageDto> dco_decode_list_chat_message_dto(dynamic raw);

  @protected
  List<GroupInfo> dco_decode_list_group_info(dynamic raw);

  @protected
  List<GroupMemberDto> dco_decode_list_group_member_dto(dynamic raw);

  @protected
  List<GroupPinDto> dco_decode_list_group_pin_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AttestationDto? dco_decode_opt_box_autoadd_attestation_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppNode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AttestationDto sse_decode_attestation_dto(SseDeserializer deserializer);

  @protected
  AuthStateDto sse_decode_auth_state_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AttestationDto sse_decode_box_autoadd_attestation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessageDto sse_decode_box_autoadd_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessageDto sse_decode_chat_message_dto(SseDeserializer deserializer);

  @protected
  GroupCreateResultDto sse_decode_group_create_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupInfo sse_decode_group_info(SseDeserializer deserializer);

  @protected
  GroupJoinResultDto sse_decode_group_join_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupMemberDto sse_decode_group_member_dto(SseDeserializer deserializer);

  @protected
  GroupPinDto sse_decode_group_pin_dto(SseDeserializer deserializer);

  @protected
  GroupStateDto sse_decode_group_state_dto(SseDeserializer deserializer);

  @protected
  IdentityDto sse_decode_identity_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChatMessageDto> sse_decode_list_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupInfo> sse_decode_list_group_info(SseDeserializer deserializer);

  @protected
  List<GroupMemberDto> sse_decode_list_group_member_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupPinDto> sse_decode_list_group_pin_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AttestationDto? sse_decode_opt_box_autoadd_attestation_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attestation_dto(
    AttestationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_state_dto(AuthStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_attestation_dto(
    AttestationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_create_result_dto(
    GroupCreateResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_info(GroupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_group_join_result_dto(
    GroupJoinResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_member_dto(
    GroupMemberDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_pin_dto(GroupPinDto self, SseSerializer serializer);

  @protected
  void sse_encode_group_state_dto(GroupStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_identity_dto(IdentityDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message_dto(
    List<ChatMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_info(
    List<GroupInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member_dto(
    List<GroupMemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_pin_dto(
    List<GroupPinDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_attestation_dto(
    AttestationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  );
}
