// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/dto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppNodePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DocManagerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FestivalRegistryCacheStorePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OffbeatNodePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PeerEntryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SyncStatusPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppNode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  FestivalRegistryCacheStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    dynamic raw,
  );

  @protected
  PeerEntry
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  DocManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    dynamic raw,
  );

  @protected
  FestivalRegistryCacheStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    dynamic raw,
  );

  @protected
  OffbeatNode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    dynamic raw,
  );

  @protected
  SyncStatus
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    dynamic raw,
  );

  @protected
  AppNode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    dynamic raw,
  );

  @protected
  DocManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    dynamic raw,
  );

  @protected
  FestivalRegistryCacheStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    dynamic raw,
  );

  @protected
  OffbeatNode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    dynamic raw,
  );

  @protected
  PeerEntry
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    dynamic raw,
  );

  @protected
  SyncStatus
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    dynamic raw,
  );

  @protected
  RustStreamSink<GroupStateDto> dco_decode_StreamSink_group_state_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<ChatMessageDto>>
  dco_decode_StreamSink_list_chat_message_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<PeerStatusInfo>>
  dco_decode_StreamSink_list_peer_status_info_Sse(dynamic raw);

  @protected
  RustStreamSink<LineupDto?>
  dco_decode_StreamSink_opt_box_autoadd_lineup_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<WeatherForecastDto?>
  dco_decode_StreamSink_opt_box_autoadd_weather_forecast_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncStatusDto> dco_decode_StreamSink_sync_status_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TransportStatusDto>
  dco_decode_StreamSink_transport_status_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArtistLinkDto dco_decode_artist_link_dto(dynamic raw);

  @protected
  ArtistProfileDto dco_decode_artist_profile_dto(dynamic raw);

  @protected
  AttestationDto dco_decode_attestation_dto(dynamic raw);

  @protected
  AuthStateDto dco_decode_auth_state_dto(dynamic raw);

  @protected
  BleStatusDto dco_decode_ble_status_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AttestationDto dco_decode_box_autoadd_attestation_dto(dynamic raw);

  @protected
  ChatMessageDto dco_decode_box_autoadd_chat_message_dto(dynamic raw);

  @protected
  FestivalCheckInDto dco_decode_box_autoadd_festival_check_in_dto(dynamic raw);

  @protected
  FestivalRegistryCacheDto dco_decode_box_autoadd_festival_registry_cache_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_16(dynamic raw);

  @protected
  LineupDto dco_decode_box_autoadd_lineup_dto(dynamic raw);

  @protected
  WeatherForecastDto dco_decode_box_autoadd_weather_forecast_dto(dynamic raw);

  @protected
  ChatMessageDto dco_decode_chat_message_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FestivalCheckInDto dco_decode_festival_check_in_dto(dynamic raw);

  @protected
  FestivalRegistryCacheDto dco_decode_festival_registry_cache_dto(dynamic raw);

  @protected
  GroupCreateResultDto dco_decode_group_create_result_dto(dynamic raw);

  @protected
  GroupInfo dco_decode_group_info(dynamic raw);

  @protected
  GroupJoinResultDto dco_decode_group_join_result_dto(dynamic raw);

  @protected
  GroupMemberDto dco_decode_group_member_dto(dynamic raw);

  @protected
  GroupPinDto dco_decode_group_pin_dto(dynamic raw);

  @protected
  GroupStateDto dco_decode_group_state_dto(dynamic raw);

  @protected
  HourlyWeatherDto dco_decode_hourly_weather_dto(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityDto dco_decode_identity_dto(dynamic raw);

  @protected
  LineupDayDto dco_decode_lineup_day_dto(dynamic raw);

  @protected
  LineupDto dco_decode_lineup_dto(dynamic raw);

  @protected
  LineupSetDto dco_decode_lineup_set_dto(dynamic raw);

  @protected
  LineupStageDto dco_decode_lineup_stage_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ArtistLinkDto> dco_decode_list_artist_link_dto(dynamic raw);

  @protected
  List<ArtistProfileDto> dco_decode_list_artist_profile_dto(dynamic raw);

  @protected
  List<ChatMessageDto> dco_decode_list_chat_message_dto(dynamic raw);

  @protected
  List<GroupInfo> dco_decode_list_group_info(dynamic raw);

  @protected
  List<GroupMemberDto> dco_decode_list_group_member_dto(dynamic raw);

  @protected
  List<GroupPinDto> dco_decode_list_group_pin_dto(dynamic raw);

  @protected
  List<LineupDayDto> dco_decode_list_lineup_day_dto(dynamic raw);

  @protected
  List<LineupSetDto> dco_decode_list_lineup_set_dto(dynamic raw);

  @protected
  List<LineupStageDto> dco_decode_list_lineup_stage_dto(dynamic raw);

  @protected
  List<MeshtasticDebugDeviceDto> dco_decode_list_meshtastic_debug_device_dto(
    dynamic raw,
  );

  @protected
  List<MeshtasticDebugFrameDto> dco_decode_list_meshtastic_debug_frame_dto(
    dynamic raw,
  );

  @protected
  List<PeerStatusInfo> dco_decode_list_peer_status_info(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ResourceSyncStatusDto> dco_decode_list_resource_sync_status_dto(
    dynamic raw,
  );

  @protected
  List<TransportPeerDto> dco_decode_list_transport_peer_dto(dynamic raw);

  @protected
  MeshtasticDebugDeviceDto dco_decode_meshtastic_debug_device_dto(dynamic raw);

  @protected
  MeshtasticDebugFrameDto dco_decode_meshtastic_debug_frame_dto(dynamic raw);

  @protected
  MeshtasticDebugReportDto dco_decode_meshtastic_debug_report_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AttestationDto? dco_decode_opt_box_autoadd_attestation_dto(dynamic raw);

  @protected
  FestivalCheckInDto? dco_decode_opt_box_autoadd_festival_check_in_dto(
    dynamic raw,
  );

  @protected
  FestivalRegistryCacheDto?
  dco_decode_opt_box_autoadd_festival_registry_cache_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_16(dynamic raw);

  @protected
  LineupDto? dco_decode_opt_box_autoadd_lineup_dto(dynamic raw);

  @protected
  WeatherForecastDto? dco_decode_opt_box_autoadd_weather_forecast_dto(
    dynamic raw,
  );

  @protected
  PeerStatusInfo dco_decode_peer_status_info(dynamic raw);

  @protected
  RelayStatusDto dco_decode_relay_status_dto(dynamic raw);

  @protected
  ResourceSyncStatusDto dco_decode_resource_sync_status_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TransportPeerDto dco_decode_transport_peer_dto(dynamic raw);

  @protected
  TransportStatusDto dco_decode_transport_status_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeatherForecastDto dco_decode_weather_forecast_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppNode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    SseDeserializer deserializer,
  );

  @protected
  PeerEntry
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  DocManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    SseDeserializer deserializer,
  );

  @protected
  OffbeatNode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatus
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SseDeserializer deserializer,
  );

  @protected
  AppNode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    SseDeserializer deserializer,
  );

  @protected
  DocManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    SseDeserializer deserializer,
  );

  @protected
  OffbeatNode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    SseDeserializer deserializer,
  );

  @protected
  PeerEntry
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatus
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GroupStateDto> sse_decode_StreamSink_group_state_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<ChatMessageDto>>
  sse_decode_StreamSink_list_chat_message_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<List<PeerStatusInfo>>
  sse_decode_StreamSink_list_peer_status_info_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<LineupDto?>
  sse_decode_StreamSink_opt_box_autoadd_lineup_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WeatherForecastDto?>
  sse_decode_StreamSink_opt_box_autoadd_weather_forecast_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatusDto> sse_decode_StreamSink_sync_status_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TransportStatusDto>
  sse_decode_StreamSink_transport_status_dto_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArtistLinkDto sse_decode_artist_link_dto(SseDeserializer deserializer);

  @protected
  ArtistProfileDto sse_decode_artist_profile_dto(SseDeserializer deserializer);

  @protected
  AttestationDto sse_decode_attestation_dto(SseDeserializer deserializer);

  @protected
  AuthStateDto sse_decode_auth_state_dto(SseDeserializer deserializer);

  @protected
  BleStatusDto sse_decode_ble_status_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AttestationDto sse_decode_box_autoadd_attestation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessageDto sse_decode_box_autoadd_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  FestivalCheckInDto sse_decode_box_autoadd_festival_check_in_dto(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheDto sse_decode_box_autoadd_festival_registry_cache_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  LineupDto sse_decode_box_autoadd_lineup_dto(SseDeserializer deserializer);

  @protected
  WeatherForecastDto sse_decode_box_autoadd_weather_forecast_dto(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessageDto sse_decode_chat_message_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FestivalCheckInDto sse_decode_festival_check_in_dto(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheDto sse_decode_festival_registry_cache_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupCreateResultDto sse_decode_group_create_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupInfo sse_decode_group_info(SseDeserializer deserializer);

  @protected
  GroupJoinResultDto sse_decode_group_join_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupMemberDto sse_decode_group_member_dto(SseDeserializer deserializer);

  @protected
  GroupPinDto sse_decode_group_pin_dto(SseDeserializer deserializer);

  @protected
  GroupStateDto sse_decode_group_state_dto(SseDeserializer deserializer);

  @protected
  HourlyWeatherDto sse_decode_hourly_weather_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityDto sse_decode_identity_dto(SseDeserializer deserializer);

  @protected
  LineupDayDto sse_decode_lineup_day_dto(SseDeserializer deserializer);

  @protected
  LineupDto sse_decode_lineup_dto(SseDeserializer deserializer);

  @protected
  LineupSetDto sse_decode_lineup_set_dto(SseDeserializer deserializer);

  @protected
  LineupStageDto sse_decode_lineup_stage_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ArtistLinkDto> sse_decode_list_artist_link_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ArtistProfileDto> sse_decode_list_artist_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ChatMessageDto> sse_decode_list_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupInfo> sse_decode_list_group_info(SseDeserializer deserializer);

  @protected
  List<GroupMemberDto> sse_decode_list_group_member_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupPinDto> sse_decode_list_group_pin_dto(SseDeserializer deserializer);

  @protected
  List<LineupDayDto> sse_decode_list_lineup_day_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LineupSetDto> sse_decode_list_lineup_set_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LineupStageDto> sse_decode_list_lineup_stage_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MeshtasticDebugDeviceDto> sse_decode_list_meshtastic_debug_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MeshtasticDebugFrameDto> sse_decode_list_meshtastic_debug_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerStatusInfo> sse_decode_list_peer_status_info(
    SseDeserializer deserializer,
  );

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ResourceSyncStatusDto> sse_decode_list_resource_sync_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransportPeerDto> sse_decode_list_transport_peer_dto(
    SseDeserializer deserializer,
  );

  @protected
  MeshtasticDebugDeviceDto sse_decode_meshtastic_debug_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  MeshtasticDebugFrameDto sse_decode_meshtastic_debug_frame_dto(
    SseDeserializer deserializer,
  );

  @protected
  MeshtasticDebugReportDto sse_decode_meshtastic_debug_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AttestationDto? sse_decode_opt_box_autoadd_attestation_dto(
    SseDeserializer deserializer,
  );

  @protected
  FestivalCheckInDto? sse_decode_opt_box_autoadd_festival_check_in_dto(
    SseDeserializer deserializer,
  );

  @protected
  FestivalRegistryCacheDto?
  sse_decode_opt_box_autoadd_festival_registry_cache_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_16(SseDeserializer deserializer);

  @protected
  LineupDto? sse_decode_opt_box_autoadd_lineup_dto(
    SseDeserializer deserializer,
  );

  @protected
  WeatherForecastDto? sse_decode_opt_box_autoadd_weather_forecast_dto(
    SseDeserializer deserializer,
  );

  @protected
  PeerStatusInfo sse_decode_peer_status_info(SseDeserializer deserializer);

  @protected
  RelayStatusDto sse_decode_relay_status_dto(SseDeserializer deserializer);

  @protected
  ResourceSyncStatusDto sse_decode_resource_sync_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TransportPeerDto sse_decode_transport_peer_dto(SseDeserializer deserializer);

  @protected
  TransportStatusDto sse_decode_transport_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeatherForecastDto sse_decode_weather_forecast_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    FestivalRegistryCacheStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    PeerEntry self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    DocManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    FestivalRegistryCacheStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    OffbeatNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SyncStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    AppNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    DocManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    FestivalRegistryCacheStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    OffbeatNode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    PeerEntry self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    SyncStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_group_state_dto_Sse(
    RustStreamSink<GroupStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_chat_message_dto_Sse(
    RustStreamSink<List<ChatMessageDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_peer_status_info_Sse(
    RustStreamSink<List<PeerStatusInfo>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_lineup_dto_Sse(
    RustStreamSink<LineupDto?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_weather_forecast_dto_Sse(
    RustStreamSink<WeatherForecastDto?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_dto_Sse(
    RustStreamSink<SyncStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transport_status_dto_Sse(
    RustStreamSink<TransportStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_artist_link_dto(ArtistLinkDto self, SseSerializer serializer);

  @protected
  void sse_encode_artist_profile_dto(
    ArtistProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_attestation_dto(
    AttestationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_state_dto(AuthStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_ble_status_dto(BleStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_attestation_dto(
    AttestationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_festival_check_in_dto(
    FestivalCheckInDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_festival_registry_cache_dto(
    FestivalRegistryCacheDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lineup_dto(
    LineupDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_weather_forecast_dto(
    WeatherForecastDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_festival_check_in_dto(
    FestivalCheckInDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_festival_registry_cache_dto(
    FestivalRegistryCacheDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_create_result_dto(
    GroupCreateResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_info(GroupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_group_join_result_dto(
    GroupJoinResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_member_dto(
    GroupMemberDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_pin_dto(GroupPinDto self, SseSerializer serializer);

  @protected
  void sse_encode_group_state_dto(GroupStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_hourly_weather_dto(
    HourlyWeatherDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_dto(IdentityDto self, SseSerializer serializer);

  @protected
  void sse_encode_lineup_day_dto(LineupDayDto self, SseSerializer serializer);

  @protected
  void sse_encode_lineup_dto(LineupDto self, SseSerializer serializer);

  @protected
  void sse_encode_lineup_set_dto(LineupSetDto self, SseSerializer serializer);

  @protected
  void sse_encode_lineup_stage_dto(
    LineupStageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist_link_dto(
    List<ArtistLinkDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_artist_profile_dto(
    List<ArtistProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_message_dto(
    List<ChatMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_info(
    List<GroupInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member_dto(
    List<GroupMemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_pin_dto(
    List<GroupPinDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lineup_day_dto(
    List<LineupDayDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lineup_set_dto(
    List<LineupSetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lineup_stage_dto(
    List<LineupStageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meshtastic_debug_device_dto(
    List<MeshtasticDebugDeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meshtastic_debug_frame_dto(
    List<MeshtasticDebugFrameDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_status_info(
    List<PeerStatusInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resource_sync_status_dto(
    List<ResourceSyncStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transport_peer_dto(
    List<TransportPeerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meshtastic_debug_device_dto(
    MeshtasticDebugDeviceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meshtastic_debug_frame_dto(
    MeshtasticDebugFrameDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meshtastic_debug_report_dto(
    MeshtasticDebugReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_attestation_dto(
    AttestationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_festival_check_in_dto(
    FestivalCheckInDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_festival_registry_cache_dto(
    FestivalRegistryCacheDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lineup_dto(
    LineupDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_weather_forecast_dto(
    WeatherForecastDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_status_info(
    PeerStatusInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relay_status_dto(
    RelayStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_sync_status_dto(
    ResourceSyncStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_transport_peer_dto(
    TransportPeerDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_status_dto(
    TransportStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weather_forecast_dto(
    WeatherForecastDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppNode(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocManager(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFestivalRegistryCacheStore(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOffbeatNode(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerEntry(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncStatus(
    int ptr,
  );
}
