// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedUpdate {
    /// raw Yrs update bytes
    #[prost(bytes = "vec", tag = "1")]
    pub update: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub author: ::prost::alloc::string::String,
    /// raw Ed25519 signature bytes
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessage {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub topic: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "6")]
    pub stage_id: ::core::option::Option<::prost::alloc::string::String>,
    /// ISO 8601 display metadata only
    #[prost(string, tag = "7")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub writer_seq: u64,
    /// per-topic Lamport clock; authoritative order
    #[prost(uint64, tag = "9")]
    pub logical_time: u64,
    /// raw 32-byte Ed25519 public key
    #[prost(bytes = "vec", tag = "10")]
    pub writer_key: ::prost::alloc::vec::Vec<u8>,
    /// Ed25519 signature over canonical public-chat bytes
    #[prost(bytes = "vec", tag = "11")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GossipEnvelope {
    #[prost(oneof = "gossip_envelope::Payload", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub payload: ::core::option::Option<gossip_envelope::Payload>,
}
/// Nested message and enum types in `GossipEnvelope`.
pub mod gossip_envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        FestivalUpdate(super::FestivalUpdate),
        #[prost(message, tag = "2")]
        GroupUpdate(super::GroupUpdate),
        #[prost(message, tag = "3")]
        Chat(super::ChatMessage),
        #[prost(message, tag = "4")]
        EncryptedChat(super::EncryptedPayload),
        #[prost(message, tag = "5")]
        SyncRequest(super::SyncRequest),
        #[prost(message, tag = "6")]
        SyncResponse(super::SyncResponse),
        #[prost(message, tag = "7")]
        SyncUpdate(super::SyncUpdate),
        #[prost(message, tag = "8")]
        ChatAuthorProof(super::ChatAuthorProof),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatAuthorProof {
    #[prost(bytes = "vec", tag = "1")]
    pub writer_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub attestation_message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub attestation_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub issuer: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FestivalUpdate {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub signed_update: ::core::option::Option<SignedUpdate>,
    #[prost(enumeration = "FestivalUpdateKind", tag = "3")]
    pub kind: i32,
    #[prost(uint64, tag = "4")]
    pub authority_seq: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupUpdate {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    /// raw ciphertext
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub group_key_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncryptedPayload {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub group_key_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncRequest {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_sv: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub group_key_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncResponse {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_diff: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub group_key_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncUpdate {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_diff: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub group_key_id: ::prost::alloc::string::String,
}
/// P2P group discovery handshake
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupHandshake {
    /// 16 random bytes
    #[prost(bytes = "vec", tag = "1")]
    pub session_nonce: ::prost::alloc::vec::Vec<u8>,
    /// blake3(key || "hs" || nonce) per group
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupHandshakeResponse {
    #[prost(message, repeated, tag = "1")]
    pub offers: ::prost::alloc::vec::Vec<GroupSyncOffer>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupSyncOffer {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    /// encrypt(group_key, yrs_state_vector)
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_sv: ::prost::alloc::vec::Vec<u8>,
    /// blake3(group_key) first 16 bytes hex
    #[prost(string, tag = "3")]
    pub group_key_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FestivalUpdateKind {
    Unspecified = 0,
    Delta = 1,
    Checkpoint = 2,
}
impl FestivalUpdateKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FESTIVAL_UPDATE_KIND_UNSPECIFIED",
            Self::Delta => "FESTIVAL_UPDATE_KIND_DELTA",
            Self::Checkpoint => "FESTIVAL_UPDATE_KIND_CHECKPOINT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FESTIVAL_UPDATE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "FESTIVAL_UPDATE_KIND_DELTA" => Some(Self::Delta),
            "FESTIVAL_UPDATE_KIND_CHECKPOINT" => Some(Self::Checkpoint),
            _ => None,
        }
    }
}
/// Client -> Server
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayClientMessage {
    #[prost(oneof = "relay_client_message::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<relay_client_message::Msg>,
}
/// Nested message and enum types in `RelayClientMessage`.
pub mod relay_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Auth(super::AuthRequest),
        #[prost(message, tag = "2")]
        Subscribe(super::SubscribeRequest),
        #[prost(message, tag = "3")]
        Unsubscribe(super::UnsubscribeRequest),
        #[prost(message, tag = "4")]
        Gossip(super::GossipRelay),
        #[prost(message, tag = "5")]
        Catchup(super::CatchupRequest),
        #[prost(message, tag = "6")]
        SvExchange(super::SvExchangeRequest),
        #[prost(message, tag = "7")]
        ChatCatchup(super::ChatCatchupRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub attestation: ::core::option::Option<Attestation>,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// deprecated legacy field
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attestation {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub issuer: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeRequest {
    #[prost(string, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsubscribeRequest {
    #[prost(string, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GossipRelay {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub message: ::core::option::Option<GossipEnvelope>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatchupRequest {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub since_seq: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SvExchangeRequest {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    /// raw Yrs state vector bytes
    #[prost(bytes = "vec", tag = "2")]
    pub sv: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatCatchupRequest {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(map = "string, uint64", tag = "2")]
    pub sv: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
    #[prost(uint32, tag = "3")]
    pub limit: u32,
    /// ID-plus-Lamport commitment at each writer's advertised sequence. Additive
    /// for compatibility with older peers that only understand the sequence map.
    #[prost(map = "string, string", tag = "4")]
    pub head_ids: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Encrypted fixed-purpose token proving possession of a private group key.
    /// Empty for public chat topics.
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_group_proof: ::prost::alloc::vec::Vec<u8>,
}
/// Server -> Client
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayServerMessage {
    #[prost(oneof = "relay_server_message::Msg", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub msg: ::core::option::Option<relay_server_message::Msg>,
}
/// Nested message and enum types in `RelayServerMessage`.
pub mod relay_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        AuthOk(super::AuthOk),
        #[prost(message, tag = "2")]
        Subscribed(super::Subscribed),
        #[prost(message, tag = "3")]
        Gossip(super::GossipBroadcast),
        #[prost(message, tag = "4")]
        Catchup(super::CatchupResponse),
        #[prost(message, tag = "5")]
        SvDiff(super::SvDiffResponse),
        #[prost(message, tag = "6")]
        ChatDiff(super::ChatDiffResponse),
        #[prost(message, tag = "7")]
        Error(super::RelayError),
        #[prost(message, tag = "8")]
        Hello(super::RelayHello),
    }
}
/// Sent by the DO immediately on WebSocket connection.
/// Contains the DO's deterministic endpoint_id so the client
/// can register it as a known peer.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayHello {
    /// hex-encoded 32-byte Ed25519 public key
    #[prost(string, tag = "1")]
    pub endpoint_id: ::prost::alloc::string::String,
    /// single-use random challenge for this socket
    #[prost(bytes = "vec", tag = "2")]
    pub auth_challenge: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub festival_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub challenge_expires_at: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AuthOk {
    #[prost(bool, tag = "1")]
    pub authenticated: bool,
    #[prost(uint32, tag = "2")]
    pub admin_count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Subscribed {
    #[prost(string, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GossipBroadcast {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub seq: u64,
    #[prost(message, optional, tag = "3")]
    pub message: ::core::option::Option<GossipEnvelope>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatchupEntry {
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    #[prost(message, optional, tag = "2")]
    pub message: ::core::option::Option<GossipEnvelope>,
    #[prost(string, tag = "3")]
    pub timestamp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatchupResponse {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<CatchupEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SvDiffResponse {
    #[prost(string, tag = "1")]
    pub doc_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub diff: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatDiffResponse {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<GossipEnvelope>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayError {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    #[prost(enumeration = "ErrorCode", tag = "2")]
    pub code: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    InvalidSignature = 1,
    Unauthorized = 2,
    RateLimited = 3,
    Malformed = 4,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::InvalidSignature => "ERROR_CODE_INVALID_SIGNATURE",
            Self::Unauthorized => "ERROR_CODE_UNAUTHORIZED",
            Self::RateLimited => "ERROR_CODE_RATE_LIMITED",
            Self::Malformed => "ERROR_CODE_MALFORMED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_INVALID_SIGNATURE" => Some(Self::InvalidSignature),
            "ERROR_CODE_UNAUTHORIZED" => Some(Self::Unauthorized),
            "ERROR_CODE_RATE_LIMITED" => Some(Self::RateLimited),
            "ERROR_CODE_MALFORMED" => Some(Self::Malformed),
            _ => None,
        }
    }
}
