// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chat_trust_label`, `month_number`, `parse_artist_links`, `parse_artist_relations`, `parse_json_string_list`, `sort_lineup_days`

/// Read lineup from a doc manager (used by watch_lineup).
///
/// Reads from top-level named maps `"stages"`, `"days"`, `"sets"` where each
/// entry is a nested YMap of fields (not JSON strings).
Future<LineupDto?> readLineupFromDoc({
  required DocManager dm,
  required String docId,
}) => RustLib.instance.api.crateApiDtoReadLineupFromDoc(dm: dm, docId: docId);

/// Read weather from a doc manager (used by get_weather / watch_weather).
///
/// Weather metadata is stored in a `"weather"` top-level map under a `"meta"`
/// entry. Hourly data is in a separate `"hourly"` top-level map keyed by time
/// string, each entry containing temp/precip/code/wind fields.
Future<WeatherForecastDto?> readWeatherFromDoc({
  required DocManager dm,
  required String docId,
}) => RustLib.instance.api.crateApiDtoReadWeatherFromDoc(dm: dm, docId: docId);

/// Convert a `PeerEntry` from the connection manager into a DTO for Flutter.
Future<PeerStatusInfo> peerEntryToDto({required PeerEntry entry}) =>
    RustLib.instance.api.crateApiDtoPeerEntryToDto(entry: entry);

/// One-shot transport snapshot (no rate computation — rates are zero).
Future<TransportStatusDto> snapshotTransport({required OffbeatNode node}) =>
    RustLib.instance.api.crateApiDtoSnapshotTransport(node: node);

/// Convert SyncStatus from notifier to DTO.
Future<SyncStatusDto> convertSyncStatus({required SyncStatus status}) =>
    RustLib.instance.api.crateApiDtoConvertSyncStatus(status: status);

/// Generate a fresh random 32-byte group key.
Future<Uint8List> generateGroupKey() =>
    RustLib.instance.api.crateApiDtoGenerateGroupKey();

/// Derive a stable group ID string from a 32-byte group key.
Future<String> groupIdFromKey({required List<int> key}) =>
    RustLib.instance.api.crateApiDtoGroupIdFromKey(key: key);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocManager>>
abstract class DocManager implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OffbeatNode>>
abstract class OffbeatNode implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerEntry>>
abstract class PeerEntry implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncStatus>>
abstract class SyncStatus implements RustOpaqueInterface {}

class ArtistLinkDto {
  final String kind;
  final String url;

  const ArtistLinkDto({required this.kind, required this.url});

  @override
  int get hashCode => kind.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistLinkDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          url == other.url;
}

class ArtistProfileDto {
  final String id;
  final String name;
  final String? mbid;
  final String? wikidataId;
  final List<String> aliases;
  final String? artistType;
  final String? country;
  final List<String> genres;
  final String? description;
  final List<ArtistLinkDto> links;
  final List<ArtistRelationDto> relations;
  final String updatedAt;

  const ArtistProfileDto({
    required this.id,
    required this.name,
    this.mbid,
    this.wikidataId,
    required this.aliases,
    this.artistType,
    this.country,
    required this.genres,
    this.description,
    required this.links,
    required this.relations,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      mbid.hashCode ^
      wikidataId.hashCode ^
      aliases.hashCode ^
      artistType.hashCode ^
      country.hashCode ^
      genres.hashCode ^
      description.hashCode ^
      links.hashCode ^
      relations.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          mbid == other.mbid &&
          wikidataId == other.wikidataId &&
          aliases == other.aliases &&
          artistType == other.artistType &&
          country == other.country &&
          genres == other.genres &&
          description == other.description &&
          links == other.links &&
          relations == other.relations &&
          updatedAt == other.updatedAt;
}

class ArtistRelationDto {
  final String kind;
  final String artistId;

  const ArtistRelationDto({required this.kind, required this.artistId});

  @override
  int get hashCode => kind.hashCode ^ artistId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistRelationDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          artistId == other.artistId;
}

class AttestationDto {
  final String message;
  final String signature;
  final String issuer;

  const AttestationDto({
    required this.message,
    required this.signature,
    required this.issuer,
  });

  @override
  int get hashCode => message.hashCode ^ signature.hashCode ^ issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttestationDto &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          issuer == other.issuer;
}

class AuthStateDto {
  final String state;
  final String? expiresAt;

  const AuthStateDto({required this.state, this.expiresAt});

  @override
  int get hashCode => state.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          expiresAt == other.expiresAt;
}

class BleStatusDto {
  final bool active;
  final int peerCount;

  /// Aggregate BLE bytes per second sent.
  final BigInt txBytesPerSec;

  /// Aggregate BLE bytes per second received.
  final BigInt rxBytesPerSec;
  final BigInt retransmits;
  final List<TransportPeerDto> peers;

  /// The list of UUIDs we are currently advertising (Discovery Beacons).
  final List<String> advertisingBeacons;

  const BleStatusDto({
    required this.active,
    required this.peerCount,
    required this.txBytesPerSec,
    required this.rxBytesPerSec,
    required this.retransmits,
    required this.peers,
    required this.advertisingBeacons,
  });

  @override
  int get hashCode =>
      active.hashCode ^
      peerCount.hashCode ^
      txBytesPerSec.hashCode ^
      rxBytesPerSec.hashCode ^
      retransmits.hashCode ^
      peers.hashCode ^
      advertisingBeacons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleStatusDto &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          peerCount == other.peerCount &&
          txBytesPerSec == other.txBytesPerSec &&
          rxBytesPerSec == other.rxBytesPerSec &&
          retransmits == other.retransmits &&
          peers == other.peers &&
          advertisingBeacons == other.advertisingBeacons;
}

class ChatMessageDto {
  final String id;
  final String userId;
  final String displayName;
  final String text;
  final String topic;
  final String? stageId;
  final String timestamp;
  final String trust;

  const ChatMessageDto({
    required this.id,
    required this.userId,
    required this.displayName,
    required this.text,
    required this.topic,
    this.stageId,
    required this.timestamp,
    required this.trust,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      displayName.hashCode ^
      text.hashCode ^
      topic.hashCode ^
      stageId.hashCode ^
      timestamp.hashCode ^
      trust.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          displayName == other.displayName &&
          text == other.text &&
          topic == other.topic &&
          stageId == other.stageId &&
          timestamp == other.timestamp &&
          trust == other.trust;
}

class FestivalCheckInDto {
  final String festivalId;
  final String kind;
  final String? value;
  final PlatformInt64 checkedAt;
  final PlatformInt64 expiresAt;
  final PlatformInt64 revision;
  final int pendingGroupCount;

  const FestivalCheckInDto({
    required this.festivalId,
    required this.kind,
    this.value,
    required this.checkedAt,
    required this.expiresAt,
    required this.revision,
    required this.pendingGroupCount,
  });

  @override
  int get hashCode =>
      festivalId.hashCode ^
      kind.hashCode ^
      value.hashCode ^
      checkedAt.hashCode ^
      expiresAt.hashCode ^
      revision.hashCode ^
      pendingGroupCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FestivalCheckInDto &&
          runtimeType == other.runtimeType &&
          festivalId == other.festivalId &&
          kind == other.kind &&
          value == other.value &&
          checkedAt == other.checkedAt &&
          expiresAt == other.expiresAt &&
          revision == other.revision &&
          pendingGroupCount == other.pendingGroupCount;
}

class FestivalRegistryCacheDto {
  final String payloadJson;
  final String fetchedAt;
  final String requestToken;

  const FestivalRegistryCacheDto({
    required this.payloadJson,
    required this.fetchedAt,
    required this.requestToken,
  });

  @override
  int get hashCode =>
      payloadJson.hashCode ^ fetchedAt.hashCode ^ requestToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FestivalRegistryCacheDto &&
          runtimeType == other.runtimeType &&
          payloadJson == other.payloadJson &&
          fetchedAt == other.fetchedAt &&
          requestToken == other.requestToken;
}

class GroupCreateResultDto {
  final String groupId;
  final String festivalId;
  final String invitePayload;

  const GroupCreateResultDto({
    required this.groupId,
    required this.festivalId,
    required this.invitePayload,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ festivalId.hashCode ^ invitePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupCreateResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          festivalId == other.festivalId &&
          invitePayload == other.invitePayload;
}

class GroupInfo {
  final String id;
  final String name;

  const GroupInfo({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class GroupJoinResultDto {
  final String groupId;
  final String festivalId;

  const GroupJoinResultDto({required this.groupId, required this.festivalId});

  @override
  int get hashCode => groupId.hashCode ^ festivalId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupJoinResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          festivalId == other.festivalId;
}

class GroupMemberDto {
  final String userId;
  final String displayName;
  final String status;
  final String locationKind;
  final String? stageId;
  final String? customLocation;
  final String? updatedAt;
  final String? expiresAt;
  final List<String> starredSetIds;

  const GroupMemberDto({
    required this.userId,
    required this.displayName,
    required this.status,
    required this.locationKind,
    this.stageId,
    this.customLocation,
    this.updatedAt,
    this.expiresAt,
    required this.starredSetIds,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      locationKind.hashCode ^
      stageId.hashCode ^
      customLocation.hashCode ^
      updatedAt.hashCode ^
      expiresAt.hashCode ^
      starredSetIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          status == other.status &&
          locationKind == other.locationKind &&
          stageId == other.stageId &&
          customLocation == other.customLocation &&
          updatedAt == other.updatedAt &&
          expiresAt == other.expiresAt &&
          starredSetIds == other.starredSetIds;
}

class GroupPinDto {
  final String id;
  final String label;
  final String location;
  final String pinnedBy;

  const GroupPinDto({
    required this.id,
    required this.label,
    required this.location,
    required this.pinnedBy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ location.hashCode ^ pinnedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupPinDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          location == other.location &&
          pinnedBy == other.pinnedBy;
}

class GroupStateDto {
  final String name;
  final List<GroupMemberDto> members;
  final List<GroupPinDto> pins;

  const GroupStateDto({
    required this.name,
    required this.members,
    required this.pins,
  });

  @override
  int get hashCode => name.hashCode ^ members.hashCode ^ pins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupStateDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          members == other.members &&
          pins == other.pins;
}

class HourlyWeatherDto {
  final List<String> time;
  final Float64List temperature2M;
  final Float64List precipitationProbability;
  final Uint32List weatherCode;
  final Float64List windSpeed10M;

  const HourlyWeatherDto({
    required this.time,
    required this.temperature2M,
    required this.precipitationProbability,
    required this.weatherCode,
    required this.windSpeed10M,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      temperature2M.hashCode ^
      precipitationProbability.hashCode ^
      weatherCode.hashCode ^
      windSpeed10M.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HourlyWeatherDto &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          temperature2M == other.temperature2M &&
          precipitationProbability == other.precipitationProbability &&
          weatherCode == other.weatherCode &&
          windSpeed10M == other.windSpeed10M;
}

class IdentityDto {
  final String userId;
  final String? displayName;

  const IdentityDto({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}

class LineupDayDto {
  final String id;
  final String label;
  final int num;
  final String month;
  final int year;

  const LineupDayDto({
    required this.id,
    required this.label,
    required this.num,
    required this.month,
    required this.year,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      num.hashCode ^
      month.hashCode ^
      year.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDayDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          num == other.num &&
          month == other.month &&
          year == other.year;
}

class LineupDto {
  final List<LineupStageDto> stages;
  final List<LineupDayDto> days;
  final List<LineupSetDto> sets;
  final List<ArtistProfileDto> artists;

  const LineupDto({
    required this.stages,
    required this.days,
    required this.sets,
    required this.artists,
  });

  @override
  int get hashCode =>
      stages.hashCode ^ days.hashCode ^ sets.hashCode ^ artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDto &&
          runtimeType == other.runtimeType &&
          stages == other.stages &&
          days == other.days &&
          sets == other.sets &&
          artists == other.artists;
}

class LineupSetDto {
  final String id;
  final String day;
  final String stage;
  final String artist;
  final String? artistMbid;
  final List<String> artistIds;
  final int startMin;
  final int durationMin;
  final String genre;
  final bool cancelled;

  const LineupSetDto({
    required this.id,
    required this.day,
    required this.stage,
    required this.artist,
    this.artistMbid,
    required this.artistIds,
    required this.startMin,
    required this.durationMin,
    required this.genre,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      day.hashCode ^
      stage.hashCode ^
      artist.hashCode ^
      artistMbid.hashCode ^
      artistIds.hashCode ^
      startMin.hashCode ^
      durationMin.hashCode ^
      genre.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupSetDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          day == other.day &&
          stage == other.stage &&
          artist == other.artist &&
          artistMbid == other.artistMbid &&
          artistIds == other.artistIds &&
          startMin == other.startMin &&
          durationMin == other.durationMin &&
          genre == other.genre &&
          cancelled == other.cancelled;
}

class LineupStageDto {
  final String id;
  final String name;
  final String short;
  final String color;
  final int order;

  const LineupStageDto({
    required this.id,
    required this.name,
    required this.short,
    required this.color,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      short.hashCode ^
      color.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupStageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          short == other.short &&
          color == other.color &&
          order == other.order;
}

class MeshtasticDebugDeviceDto {
  final String deviceId;
  final String? name;
  final int? rssi;
  final List<String> services;

  const MeshtasticDebugDeviceDto({
    required this.deviceId,
    this.name,
    this.rssi,
    required this.services,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ name.hashCode ^ rssi.hashCode ^ services.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshtasticDebugDeviceDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          rssi == other.rssi &&
          services == other.services;
}

class MeshtasticDebugFrameDto {
  final String kind;
  final String topicTagHex;
  final String messageIdHex;
  final String bodyHex;
  final String? bodyText;

  const MeshtasticDebugFrameDto({
    required this.kind,
    required this.topicTagHex,
    required this.messageIdHex,
    required this.bodyHex,
    this.bodyText,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      topicTagHex.hashCode ^
      messageIdHex.hashCode ^
      bodyHex.hashCode ^
      bodyText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshtasticDebugFrameDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          topicTagHex == other.topicTagHex &&
          messageIdHex == other.messageIdHex &&
          bodyHex == other.bodyHex &&
          bodyText == other.bodyText;
}

class MeshtasticDebugReportDto {
  final String deviceId;
  final bool connected;
  final int mtu;
  final List<String> services;
  final int sentFragments;
  final int rawFromRadioCount;
  final int privateAppCount;
  final int appliedGroupChats;
  final List<MeshtasticDebugFrameDto> receivedFrames;
  final List<String> events;

  const MeshtasticDebugReportDto({
    required this.deviceId,
    required this.connected,
    required this.mtu,
    required this.services,
    required this.sentFragments,
    required this.rawFromRadioCount,
    required this.privateAppCount,
    required this.appliedGroupChats,
    required this.receivedFrames,
    required this.events,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      connected.hashCode ^
      mtu.hashCode ^
      services.hashCode ^
      sentFragments.hashCode ^
      rawFromRadioCount.hashCode ^
      privateAppCount.hashCode ^
      appliedGroupChats.hashCode ^
      receivedFrames.hashCode ^
      events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshtasticDebugReportDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          connected == other.connected &&
          mtu == other.mtu &&
          services == other.services &&
          sentFragments == other.sentFragments &&
          rawFromRadioCount == other.rawFromRadioCount &&
          privateAppCount == other.privateAppCount &&
          appliedGroupChats == other.appliedGroupChats &&
          receivedFrames == other.receivedFrames &&
          events == other.events;
}

/// A simplified view of a tracked peer for the Flutter UI.
class PeerStatusInfo {
  final String endpointId;

  /// Discovery source: "crdt", "ble", or "gossip".
  final String source;

  /// Gossip connection status: "unknown", "joining", "active", or "stale".
  final String status;
  final bool bleVisible;
  final String? relayUrl;

  const PeerStatusInfo({
    required this.endpointId,
    required this.source,
    required this.status,
    required this.bleVisible,
    this.relayUrl,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^
      source.hashCode ^
      status.hashCode ^
      bleVisible.hashCode ^
      relayUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerStatusInfo &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          source == other.source &&
          status == other.status &&
          bleVisible == other.bleVisible &&
          relayUrl == other.relayUrl;
}

class RelayStatusDto {
  final bool connected;
  final bool authenticated;

  /// Bytes per second sent to the relay (computed over last interval).
  final BigInt txBytesPerSec;

  /// Bytes per second received from the relay.
  final BigInt rxBytesPerSec;

  const RelayStatusDto({
    required this.connected,
    required this.authenticated,
    required this.txBytesPerSec,
    required this.rxBytesPerSec,
  });

  @override
  int get hashCode =>
      connected.hashCode ^
      authenticated.hashCode ^
      txBytesPerSec.hashCode ^
      rxBytesPerSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusDto &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          authenticated == other.authenticated &&
          txBytesPerSec == other.txBytesPerSec &&
          rxBytesPerSec == other.rxBytesPerSec;
}

/// Per-resource sync status.
class ResourceSyncStatusDto {
  final String id;
  final bool syncing;
  final String? lastSynced;
  final String? error;
  final int messagesReceived;
  final int messagesSent;

  /// Number of peers subscribed to this topic on the relay.
  final int peerCount;

  const ResourceSyncStatusDto({
    required this.id,
    required this.syncing,
    this.lastSynced,
    this.error,
    required this.messagesReceived,
    required this.messagesSent,
    required this.peerCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      syncing.hashCode ^
      lastSynced.hashCode ^
      error.hashCode ^
      messagesReceived.hashCode ^
      messagesSent.hashCode ^
      peerCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceSyncStatusDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncing == other.syncing &&
          lastSynced == other.lastSynced &&
          error == other.error &&
          messagesReceived == other.messagesReceived &&
          messagesSent == other.messagesSent &&
          peerCount == other.peerCount;
}

/// Overall sync status for the node.
class SyncStatusDto {
  final bool syncing;
  final List<ResourceSyncStatusDto> resources;
  final int pendingOps;

  const SyncStatusDto({
    required this.syncing,
    required this.resources,
    required this.pendingOps,
  });

  @override
  int get hashCode =>
      syncing.hashCode ^ resources.hashCode ^ pendingOps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          syncing == other.syncing &&
          resources == other.resources &&
          pendingOps == other.pendingOps;
}

class TransportPeerDto {
  final String deviceId;
  final String phase;
  final String? connectPath;
  final String? verifiedEndpoint;
  final int consecutiveFailures;

  /// The 12-byte prefix seen in the peer's advertisement.
  final String? keyPrefix;

  const TransportPeerDto({
    required this.deviceId,
    required this.phase,
    this.connectPath,
    this.verifiedEndpoint,
    required this.consecutiveFailures,
    this.keyPrefix,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      phase.hashCode ^
      connectPath.hashCode ^
      verifiedEndpoint.hashCode ^
      consecutiveFailures.hashCode ^
      keyPrefix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportPeerDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          phase == other.phase &&
          connectPath == other.connectPath &&
          verifiedEndpoint == other.verifiedEndpoint &&
          consecutiveFailures == other.consecutiveFailures &&
          keyPrefix == other.keyPrefix;
}

class TransportStatusDto {
  /// Relay (Festival DO WebSocket) connection status.
  final RelayStatusDto relay;

  /// BLE transport status.
  final BleStatusDto ble;

  const TransportStatusDto({required this.relay, required this.ble});

  @override
  int get hashCode => relay.hashCode ^ ble.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportStatusDto &&
          runtimeType == other.runtimeType &&
          relay == other.relay &&
          ble == other.ble;
}

class WeatherForecastDto {
  final String updatedAt;
  final double lat;
  final double lon;
  final String timezone;
  final HourlyWeatherDto hourly;

  const WeatherForecastDto({
    required this.updatedAt,
    required this.lat,
    required this.lon,
    required this.timezone,
    required this.hourly,
  });

  @override
  int get hashCode =>
      updatedAt.hashCode ^
      lat.hashCode ^
      lon.hashCode ^
      timezone.hashCode ^
      hourly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherForecastDto &&
          runtimeType == other.runtimeType &&
          updatedAt == other.updatedAt &&
          lat == other.lat &&
          lon == other.lon &&
          timezone == other.timezone &&
          hourly == other.hourly;
}
