// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `parse_json_array`

/// Read lineup from a doc manager (used by watch_lineup).
Future<LineupDto?> readLineupFromDoc({
  required DocManager dm,
  required String docId,
}) => RustLib.instance.api.crateApiDtoReadLineupFromDoc(dm: dm, docId: docId);

/// Read weather from a doc manager (used by get_weather / watch_weather).
Future<WeatherForecastDto?> readWeatherFromDoc({
  required DocManager dm,
  required String docId,
}) => RustLib.instance.api.crateApiDtoReadWeatherFromDoc(dm: dm, docId: docId);

/// Convert a `PeerEntry` from the connection manager into a DTO for Flutter.
Future<PeerStatusInfo> peerEntryToDto({required PeerEntry entry}) =>
    RustLib.instance.api.crateApiDtoPeerEntryToDto(entry: entry);

/// One-shot transport snapshot (no rate computation — rates are zero).
Future<TransportStatusDto> snapshotTransport({required OffbeatNode node}) =>
    RustLib.instance.api.crateApiDtoSnapshotTransport(node: node);

/// Convert SyncStatus from notifier to DTO.
Future<SyncStatusDto> convertSyncStatus({required SyncStatus status}) =>
    RustLib.instance.api.crateApiDtoConvertSyncStatus(status: status);

/// Generate a fresh random 32-byte group key.
Future<Uint8List> generateGroupKey() =>
    RustLib.instance.api.crateApiDtoGenerateGroupKey();

/// Derive a stable group ID string from a 32-byte group key.
Future<String> groupIdFromKey({required List<int> key}) =>
    RustLib.instance.api.crateApiDtoGroupIdFromKey(key: key);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocManager>>
abstract class DocManager implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OffbeatNode>>
abstract class OffbeatNode implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerEntry>>
abstract class PeerEntry implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncStatus>>
abstract class SyncStatus implements RustOpaqueInterface {}

class AttestationDto {
  final String message;
  final String signature;
  final String issuer;

  const AttestationDto({
    required this.message,
    required this.signature,
    required this.issuer,
  });

  @override
  int get hashCode => message.hashCode ^ signature.hashCode ^ issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttestationDto &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          signature == other.signature &&
          issuer == other.issuer;
}

class AuthStateDto {
  final String state;
  final String? expiresAt;

  const AuthStateDto({required this.state, this.expiresAt});

  @override
  int get hashCode => state.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          expiresAt == other.expiresAt;
}

class BleStatusDto {
  final bool active;
  final int peerCount;

  /// Aggregate BLE bytes per second sent.
  final BigInt txBytesPerSec;

  /// Aggregate BLE bytes per second received.
  final BigInt rxBytesPerSec;
  final BigInt retransmits;
  final List<TransportPeerDto> peers;

  const BleStatusDto({
    required this.active,
    required this.peerCount,
    required this.txBytesPerSec,
    required this.rxBytesPerSec,
    required this.retransmits,
    required this.peers,
  });

  @override
  int get hashCode =>
      active.hashCode ^
      peerCount.hashCode ^
      txBytesPerSec.hashCode ^
      rxBytesPerSec.hashCode ^
      retransmits.hashCode ^
      peers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleStatusDto &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          peerCount == other.peerCount &&
          txBytesPerSec == other.txBytesPerSec &&
          rxBytesPerSec == other.rxBytesPerSec &&
          retransmits == other.retransmits &&
          peers == other.peers;
}

class ChatMessageDto {
  final String id;
  final String userId;
  final String displayName;
  final String text;
  final String topic;
  final String? stageId;
  final String timestamp;

  const ChatMessageDto({
    required this.id,
    required this.userId,
    required this.displayName,
    required this.text,
    required this.topic,
    this.stageId,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      displayName.hashCode ^
      text.hashCode ^
      topic.hashCode ^
      stageId.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          displayName == other.displayName &&
          text == other.text &&
          topic == other.topic &&
          stageId == other.stageId &&
          timestamp == other.timestamp;
}

class GroupCreateResultDto {
  final String groupId;
  final String festivalId;
  final String invitePayload;

  const GroupCreateResultDto({
    required this.groupId,
    required this.festivalId,
    required this.invitePayload,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ festivalId.hashCode ^ invitePayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupCreateResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          festivalId == other.festivalId &&
          invitePayload == other.invitePayload;
}

class GroupInfo {
  final String id;
  final String name;

  const GroupInfo({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class GroupJoinResultDto {
  final String groupId;
  final String festivalId;

  const GroupJoinResultDto({required this.groupId, required this.festivalId});

  @override
  int get hashCode => groupId.hashCode ^ festivalId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupJoinResultDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          festivalId == other.festivalId;
}

class GroupMemberDto {
  final String userId;
  final String displayName;
  final String status;
  final String? stageId;
  final String? customLocation;

  const GroupMemberDto({
    required this.userId,
    required this.displayName,
    required this.status,
    this.stageId,
    this.customLocation,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      stageId.hashCode ^
      customLocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          status == other.status &&
          stageId == other.stageId &&
          customLocation == other.customLocation;
}

class GroupPinDto {
  final String id;
  final String label;
  final String location;
  final String pinnedBy;

  const GroupPinDto({
    required this.id,
    required this.label,
    required this.location,
    required this.pinnedBy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ location.hashCode ^ pinnedBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupPinDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          location == other.location &&
          pinnedBy == other.pinnedBy;
}

class GroupStateDto {
  final String name;
  final List<GroupMemberDto> members;
  final List<GroupPinDto> pins;

  const GroupStateDto({
    required this.name,
    required this.members,
    required this.pins,
  });

  @override
  int get hashCode => name.hashCode ^ members.hashCode ^ pins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupStateDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          members == other.members &&
          pins == other.pins;
}

class HourlyWeatherDto {
  final List<String> time;
  final Float64List temperature2M;
  final Float64List precipitationProbability;
  final Uint32List weatherCode;
  final Float64List windSpeed10M;

  const HourlyWeatherDto({
    required this.time,
    required this.temperature2M,
    required this.precipitationProbability,
    required this.weatherCode,
    required this.windSpeed10M,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      temperature2M.hashCode ^
      precipitationProbability.hashCode ^
      weatherCode.hashCode ^
      windSpeed10M.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HourlyWeatherDto &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          temperature2M == other.temperature2M &&
          precipitationProbability == other.precipitationProbability &&
          weatherCode == other.weatherCode &&
          windSpeed10M == other.windSpeed10M;
}

class IdentityDto {
  final String userId;
  final String? displayName;

  const IdentityDto({required this.userId, this.displayName});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName;
}

class LineupDayDto {
  final String id;
  final String label;
  final int num;
  final String month;
  final int year;

  const LineupDayDto({
    required this.id,
    required this.label,
    required this.num,
    required this.month,
    required this.year,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      num.hashCode ^
      month.hashCode ^
      year.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDayDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          num == other.num &&
          month == other.month &&
          year == other.year;
}

class LineupDto {
  final List<LineupStageDto> stages;
  final List<LineupDayDto> days;
  final List<LineupSetDto> sets;

  const LineupDto({
    required this.stages,
    required this.days,
    required this.sets,
  });

  @override
  int get hashCode => stages.hashCode ^ days.hashCode ^ sets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupDto &&
          runtimeType == other.runtimeType &&
          stages == other.stages &&
          days == other.days &&
          sets == other.sets;
}

class LineupSetDto {
  final String id;
  final String day;
  final String stage;
  final String artist;
  final int startMin;
  final int durationMin;
  final String genre;
  final bool cancelled;

  const LineupSetDto({
    required this.id,
    required this.day,
    required this.stage,
    required this.artist,
    required this.startMin,
    required this.durationMin,
    required this.genre,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      day.hashCode ^
      stage.hashCode ^
      artist.hashCode ^
      startMin.hashCode ^
      durationMin.hashCode ^
      genre.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupSetDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          day == other.day &&
          stage == other.stage &&
          artist == other.artist &&
          startMin == other.startMin &&
          durationMin == other.durationMin &&
          genre == other.genre &&
          cancelled == other.cancelled;
}

class LineupStageDto {
  final String id;
  final String name;
  final String short;
  final String color;
  final int order;

  const LineupStageDto({
    required this.id,
    required this.name,
    required this.short,
    required this.color,
    required this.order,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      short.hashCode ^
      color.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineupStageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          short == other.short &&
          color == other.color &&
          order == other.order;
}

/// A simplified view of a tracked peer for the Flutter UI.
class PeerStatusInfo {
  final String endpointId;

  /// Discovery source: "crdt", "ble", or "gossip".
  final String source;

  /// Gossip connection status: "unknown", "joining", "active", or "stale".
  final String status;
  final bool bleVisible;
  final String? relayUrl;

  const PeerStatusInfo({
    required this.endpointId,
    required this.source,
    required this.status,
    required this.bleVisible,
    this.relayUrl,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^
      source.hashCode ^
      status.hashCode ^
      bleVisible.hashCode ^
      relayUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerStatusInfo &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          source == other.source &&
          status == other.status &&
          bleVisible == other.bleVisible &&
          relayUrl == other.relayUrl;
}

class RelayStatusDto {
  final bool connected;
  final bool authenticated;

  /// Bytes per second sent to the relay (computed over last interval).
  final BigInt txBytesPerSec;

  /// Bytes per second received from the relay.
  final BigInt rxBytesPerSec;

  const RelayStatusDto({
    required this.connected,
    required this.authenticated,
    required this.txBytesPerSec,
    required this.rxBytesPerSec,
  });

  @override
  int get hashCode =>
      connected.hashCode ^
      authenticated.hashCode ^
      txBytesPerSec.hashCode ^
      rxBytesPerSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusDto &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          authenticated == other.authenticated &&
          txBytesPerSec == other.txBytesPerSec &&
          rxBytesPerSec == other.rxBytesPerSec;
}

/// Per-resource sync status.
class ResourceSyncStatusDto {
  final String id;
  final bool syncing;
  final String? lastSynced;
  final String? error;
  final int messagesReceived;
  final int messagesSent;

  /// Number of peers subscribed to this topic on the relay.
  final int peerCount;

  const ResourceSyncStatusDto({
    required this.id,
    required this.syncing,
    this.lastSynced,
    this.error,
    required this.messagesReceived,
    required this.messagesSent,
    required this.peerCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      syncing.hashCode ^
      lastSynced.hashCode ^
      error.hashCode ^
      messagesReceived.hashCode ^
      messagesSent.hashCode ^
      peerCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceSyncStatusDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncing == other.syncing &&
          lastSynced == other.lastSynced &&
          error == other.error &&
          messagesReceived == other.messagesReceived &&
          messagesSent == other.messagesSent &&
          peerCount == other.peerCount;
}

/// Overall sync status for the node.
class SyncStatusDto {
  final bool syncing;
  final List<ResourceSyncStatusDto> resources;
  final int pendingOps;

  const SyncStatusDto({
    required this.syncing,
    required this.resources,
    required this.pendingOps,
  });

  @override
  int get hashCode =>
      syncing.hashCode ^ resources.hashCode ^ pendingOps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          syncing == other.syncing &&
          resources == other.resources &&
          pendingOps == other.pendingOps;
}

class TransportPeerDto {
  final String deviceId;
  final String phase;
  final String? connectPath;
  final String? verifiedEndpoint;
  final int consecutiveFailures;

  const TransportPeerDto({
    required this.deviceId,
    required this.phase,
    this.connectPath,
    this.verifiedEndpoint,
    required this.consecutiveFailures,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      phase.hashCode ^
      connectPath.hashCode ^
      verifiedEndpoint.hashCode ^
      consecutiveFailures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportPeerDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          phase == other.phase &&
          connectPath == other.connectPath &&
          verifiedEndpoint == other.verifiedEndpoint &&
          consecutiveFailures == other.consecutiveFailures;
}

class TransportStatusDto {
  /// Relay (Festival DO WebSocket) connection status.
  final RelayStatusDto relay;

  /// BLE transport status.
  final BleStatusDto ble;

  const TransportStatusDto({required this.relay, required this.ble});

  @override
  int get hashCode => relay.hashCode ^ ble.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportStatusDto &&
          runtimeType == other.runtimeType &&
          relay == other.relay &&
          ble == other.ble;
}

class WeatherForecastDto {
  final String updatedAt;
  final double lat;
  final double lon;
  final String timezone;
  final HourlyWeatherDto hourly;

  const WeatherForecastDto({
    required this.updatedAt,
    required this.lat,
    required this.lon,
    required this.timezone,
    required this.hourly,
  });

  @override
  int get hashCode =>
      updatedAt.hashCode ^
      lat.hashCode ^
      lon.hashCode ^
      timezone.hashCode ^
      hourly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherForecastDto &&
          runtimeType == other.runtimeType &&
          updatedAt == other.updatedAt &&
          lat == other.lat &&
          lon == other.lon &&
          timezone == other.timezone &&
          hourly == other.hourly;
}
